# Extends https://github.com/mundialis/github-workflows/blob/main/linting-config-examples/ruff.toml

lint.ignore = [
    "BLE001",  # BLE001 Do not catch blind exception: `Exception
    "D205",
    "E501",  # ignore here, flake checks with 88 lines
    "RUF012",
    "S108",
]

# [lint.per-file-ignores]
# "src/actinia_grassdata_management_plugin/apidocs/__init__.py" = [ "E501",]
